export {default as About } from './about/About'
export {default as Contribution} from './contribution/Contribution'
export {default as Header} from './header/Header'
export {default as Newsletter} from './newsletter/Newsletter'
export {default as Reasons} from './reasons/Reasons'
export {default as TakeAction} from './takeAction/TakeAction'
export {default as WhyUs} from './whyUs/WhyUs'